name: ReconnectCooldown
main: com.battleasya.reconnectcooldown.ReconnectCooldown
version: 1.0.0
author: Dennie
website: http://battleasya.com
description: Reconnect Cooldown System
commands:
  rccdreload:
    description: Reload config.
permissions:
  rccd.reload:
    default: op